# Generated by Django 5.1.15 on 2026-09-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('blog_status', 'Blog status update'), ('video_status', 'Video status update'), ('course_status', 'Course status update'), ('comment_reply', 'Comment reply')], max_length=20),
        ),
    ]
