# Generated by Django 5.1.15 on 2026-10-08 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0006_review_reply_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('blog_status', 'Blog status update'), ('video_status', 'Video status update'), ('course_status', 'Course status update'), ('course_review', 'New course review'), ('review_reply', 'Reply to a course review'), ('certificate', 'Certificate earned'), ('comment_reply', 'Comment reply')], max_length=20),
        ),
    ]
