# Generated by Django 5.1.15 on 2026-09-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_cover_photo'),
        ('pages', '0032_seed_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='expertise',
            field=models.ManyToManyField(blank=True, help_text='Up to 3 — shown on the public profile and author cards.', related_name='expert_users', to='pages.topic'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_title',
            field=models.CharField(blank=True, help_text="Job title/role at their company, e.g. 'Deputy GM, Grid Operations'", max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
