# Generated by Django 5.1.15 on 2026-09-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_professional_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(choices=[('learner', 'Learner'), ('professional', 'Professional')], default='learner', max_length=20),
        ),
    ]
