# Generated by Django 5.1.15 on 2026-09-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_admin_only_backoffice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, help_text='Full name shown publicly on the profile, bylines and comments.', max_length=150),
        ),
    ]
