# Generated by Django 5.1.15 on 2026-09-29 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_display_name_help_text'),
        # Content must copy its tier into `access` before the tier table goes.
        ('pages', '0035_access_replaces_tiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='membership_tier',
        ),
        migrations.DeleteModel(
            name='MembershipTier',
        ),
    ]
