# Generated by Django 5.1.15 on 2026-10-01 06:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_membership_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.'),
        ),
        migrations.AddField(
            model_name='user',
            name='gelearn_rating',
            field=models.DecimalField(blank=True, decimal_places=1, help_text="0.0 to 5.0, set by Genex. Shown on the Professional's cards.", max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))]),
        ),
        migrations.AddField(
            model_name='user',
            name='is_featured',
            field=models.BooleanField(default=False, help_text="Show in 'Our Leading Professionals' on the GeLearn home page."),
        ),
    ]
