# Generated by Django 5.1.15 on 2026-10-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_gelearn_phase1'),
        ('learning', '0003_seed_career_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='career_goal',
            field=models.ForeignKey(blank=True, help_text='The role this person is working toward; GeLearn suggests courses for it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='learning.careerrole'),
        ),
    ]
