# Generated by Django 5.1.15 on 2026-10-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_gelearn_phase2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_certificates',
            field=models.BooleanField(default=False, help_text="The learner's choice: list their GeLearn certificates on their public profile.", verbose_name='Show certificates on public profile'),
        ),
    ]
