# Generated by Django 6.1 on 2026-09-05 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='required_tier',
            field=models.ForeignKey(blank=True, help_text='Leave blank for public access. Set to require this tier or higher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membershiptier'),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='required_tier',
            field=models.ForeignKey(blank=True, help_text='Leave blank for public access. Set to require this tier or higher.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.membershiptier'),
        ),
        migrations.CreateModel(
            name='UserBlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('published', 'Published'), ('rejected', 'Rejected')], default='draft', max_length=10)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_submissions', to=settings.AUTH_USER_MODEL)),
                ('published_post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_source', to='pages.blogpost')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Blog Submission',
                'ordering': ['-created_at'],
            },
        ),
    ]
