# Generated by Django 5.1.15 on 2026-09-07 11:45

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_podcastepisode_required_tier_videoitem_required_tier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_slides',
            field=wagtail.fields.StreamField([('slide', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('video', 'Video'), ('image', 'Image')]}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 4: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload a video file (mp4) for this slide', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'required': False}), 6: ('wagtail.blocks.StructBlock', [[('headline', 0), ('subline', 1), ('media_type', 2), ('background_image', 3), ('background_video', 4), ('cta_text', 5), ('cta_link', 5)]], {})}),
        ),
    ]
