# Generated by Django 5.1.15 on 2026-09-07 11:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_homepage_hero_slides'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='credibility_strip',
            field=wagtail.fields.StreamField([('client', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Client name — used for accessible alt text only, not displayed'}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Small logo, ideally transparent background'}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('logo', 1)]], {})}),
        ),
    ]
