# Generated by Django 5.1.15 on 2026-09-08 06:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_homepage_credibility_strip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='projects_showcase',
            field=wagtail.fields.StreamField([('item', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('location', 1), ('metric', 1), ('image', 2), ('href', 1)]], {})}),
        ),
    ]
