# Generated by Django 5.1.15 on 2026-09-08 06:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_homepage_projects_showcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='edge_section',
            field=wagtail.fields.StreamField([('section', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Why Genex.', 'help_text': 'Section title shown above the statements', 'required': False}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Control room image', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {}), 3: ('wagtail.blocks.TextBlock', (), {}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('body', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'min_num': 1}), 6: ('wagtail.blocks.StructBlock', [[('heading', 0), ('image', 1), ('statements', 5)]], {})}),
        ),
    ]
