# Generated by Django 5.1.15 on 2026-09-08 07:05

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_homepage_world_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='world_map',
            field=wagtail.fields.StreamField([('map', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Global Presence', 'help_text': 'Small label above the heading', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Operating Worldwide.', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.ListBlock', (2,), {'default': [], 'help_text': 'Paragraphs shown under the heading', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {'default': [], 'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('value', 4), ('suffix', 6), ('label', 4)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'help_text': 'Stats strip — add or remove freely'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': "Country code e.g. 'IN', 'US'", 'max_length': 5}), 10: ('wagtail.blocks.FloatBlock', (), {}), 11: ('wagtail.blocks.FloatBlock', (), {'default': 0.0, 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('id', 9), ('name', 4), ('latitude', 10), ('longitude', 10), ('delay', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('description', 3), ('bullet_points', 5), ('stats', 8), ('pins', 13)]], {})}),
        ),
    ]
