# Generated by Django 5.1.15 on 2026-09-08 11:11

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_homepage_world_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='gelearn_teaser',
            field=wagtail.fields.StreamField([('card', 3)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "URL slug e.g. 'how-we-work'"}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('LanguageOutlined', 'Language / Globe'), ('ShieldOutlined', 'Shield'), ('VerifiedOutlined', 'Verified'), ('BoltOutlined', 'Bolt (outlined)'), ('SecurityOutlined', 'Security'), ('CheckCircleOutlined', 'Check Circle'), ('EngineeringOutlined', 'Engineering'), ('MemoryOutlined', 'Memory'), ('DescriptionOutlined', 'Description'), ('GavelOutlined', 'Gavel'), ('ArticleOutlined', 'Article'), ('PlayCircleOutlined', 'Play Circle'), ('RssFeedOutlined', 'RSS Feed'), ('HelpOutlined', 'Help / FAQ'), ('MicOutlined', 'Microphone / Podcast'), ('Bolt', 'Bolt (filled)'), ('TrendingUp', 'Trending Up'), ('Groups', 'Groups / Team'), ('LocationOn', 'Location'), ('Phone', 'Phone'), ('Email', 'Email'), ('Chat', 'Chat / WhatsApp'), ('ElectricBolt', 'Electric Bolt'), ('SolarPower', 'Solar Power'), ('WindPower', 'Wind Power'), ('BatteryChargingFull', 'Battery'), ('EvStation', 'EV Station'), ('Analytics', 'Analytics'), ('Dashboard', 'Dashboard'), ('Memory', 'Memory'), ('Storage', 'Server / Storage'), ('Cloud', 'Cloud'), ('Wifi', 'IoT / Wifi'), ('Psychology', 'AI / Brain'), ('AutoAwesome', 'AI / Sparkles'), ('Business', 'Company'), ('Factory', 'Factory'), ('Engineering', 'Engineering'), ('Science', 'R&D'), ('CurrencyRupee', 'Indian Rupee'), ('AccountBalance', 'Finance'), ('Handshake', 'Partnership'), ('EmojiObjects', 'Innovation'), ('Timeline', 'Timeline'), ('Star', 'Star'), ('Work', 'Jobs'), ('WorkspacePremiumOutlined', 'Award / Premium'), ('EmojiEventsOutlined', 'Trophy / Event'), ('LinkedIn', 'LinkedIn')]}), 3: ('wagtail.blocks.StructBlock', [[('slug', 0), ('label', 1), ('icon', 2)]], {})}),
        ),
    ]
