# Generated by Django 5.1.15 on 2026-09-08 11:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_homepage_gelearn_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='tech_partners',
            field=wagtail.fields.StreamField([('partner', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Full name e.g. 'Amazon Web Services'"}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Short display name e.g. 'AWS'"}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Small partner/standard logo — shown instead of the abbreviation text', 'required': False}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('abbr', 1), ('href', 2), ('logo', 3)]], {})}),
        ),
    ]
