# Generated by Django 5.1.15 on 2026-09-09 11:43
# Hand-edited: reordered into AddField -> RunPython (data migration) -> RemoveField
# so old field values are still readable when the data migration runs, and to
# preserve real published content from ProductPage/InnovationPage's old
# overview/capabilities/tech_highlights/stats/cta fields into the new `body`
# StreamField instead of losing it. `gradient` carried no user-authored content
# (a decorative Tailwind class choice) so it's just dropped, no data to migrate.

import uuid

import wagtail.fields
from django.db import migrations


def _new_block(block_type, value):
    return {"type": block_type, "value": value, "id": str(uuid.uuid4())}


def _plain(value):
    """Recursively convert a rehydrated Wagtail block value (StructValue/StreamValue/
    ListValue, dict-subclass-like objects) into a plain JSON-safe dict/list/scalar,
    so it can be embedded as-is into a new StreamField's raw stream data."""
    if hasattr(value, "items"):
        return {k: _plain(v) for k, v in dict(value).items()}
    if isinstance(value, (list, tuple)) or hasattr(value, "__iter__") and not isinstance(value, str):
        try:
            return [_plain(v) for v in value]
        except TypeError:
            return value
    return value


def migrate_product_and_innovation_bodies(apps, schema_editor):
    """Reshape old ProductPage/InnovationPage fields into the new `body` StreamField.

    Historical-model StreamField access still returns rehydrated block objects
    (StreamValue of StreamChild, each with `.block_type`/`.value`) rather than raw
    JSON dicts, so each block's value is unwrapped via `_plain()` before being
    embedded into the new body's plain dict/list structure.
    """

    def convert(page_model):
        for page in page_model.objects.all():
            body = []

            paragraphs = [_plain(b.value) for b in (page.overview or [])]
            if paragraphs:
                body.append(_new_block("overview", {
                    "heading": "Overview",
                    "paragraphs": paragraphs,
                }))

            items = [_plain(b.value) for b in (page.capabilities or [])]
            if items:
                body.append(_new_block("capabilities", {
                    "heading": "Capabilities",
                    "items": items,
                }))

            highlights = [_plain(b.value) for b in (page.tech_highlights or [])]
            if highlights:
                body.append(_new_block("tech_highlights", {
                    "eyebrow": "Built for Reliability",
                    "intro": "Purpose-engineered for the complexity of India's power infrastructure — built to last and scale.",
                    "items": highlights,
                }))

            stats = [_plain(b.value) for b in (page.stats or [])]
            if stats:
                body.append(_new_block("stats", {
                    "heading": "",
                    "bg": "",
                    "stats": stats,
                }))

            cta_blocks = list(page.cta or [])
            if cta_blocks:
                # Old `cta` StreamField could technically hold more than one block,
                # but only a single CTA band has ever been used in practice.
                body.append(_new_block("cta", _plain(cta_blocks[0].value)))

            page.body = body
            page.save()

    convert(apps.get_model("pages", "ProductPage"))
    convert(apps.get_model("pages", "InnovationPage"))


def reverse_irreversible(apps, schema_editor):
    raise migrations.exceptions.IrreversibleError(
        "0011_productpage_innovationpage_body cannot be reversed: the source "
        "fields (overview/capabilities/tech_highlights/stats/cta/gradient) are "
        "dropped by RemoveField in this same migration. Restore from a "
        "pre-migration database backup instead."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_homepage_tech_partners'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationpage',
            name='body',
            field=wagtail.fields.StreamField([('overview', 3), ('capabilities', 7), ('tech_highlights', 14), ('deployment_steps', 21), ('video_section', 26), ('testimonials_section', 31), ('stats', 35), ('compliance_note', 37), ('documents', 41), ('faq_section', 45), ('cta', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Overview', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'min_num': 1}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('paragraphs', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Capabilities', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'min_num': 1}), 7: ('wagtail.blocks.StructBlock', [[('heading', 4), ('items', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Built for Reliability', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'default': "Purpose-engineered for the complexity of India's power infrastructure — built to last and scale.", 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Protocol Support'"}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Modbus, DNP3, IEC 61850'"}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('eyebrow', 8), ('intro', 9), ('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': "How It's Deployed", 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': "'01', '02', etc.", 'max_length': 3}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('LanguageOutlined', 'Language / Globe'), ('ShieldOutlined', 'Shield'), ('VerifiedOutlined', 'Verified'), ('BoltOutlined', 'Bolt (outlined)'), ('SecurityOutlined', 'Security'), ('CheckCircleOutlined', 'Check Circle'), ('EngineeringOutlined', 'Engineering'), ('MemoryOutlined', 'Memory'), ('DescriptionOutlined', 'Description'), ('GavelOutlined', 'Gavel'), ('ArticleOutlined', 'Article'), ('PlayCircleOutlined', 'Play Circle'), ('RssFeedOutlined', 'RSS Feed'), ('HelpOutlined', 'Help / FAQ'), ('MicOutlined', 'Microphone / Podcast'), ('Bolt', 'Bolt (filled)'), ('TrendingUp', 'Trending Up'), ('Groups', 'Groups / Team'), ('LocationOn', 'Location'), ('Phone', 'Phone'), ('Email', 'Email'), ('Chat', 'Chat / WhatsApp'), ('ElectricBolt', 'Electric Bolt'), ('SolarPower', 'Solar Power'), ('WindPower', 'Wind Power'), ('BatteryChargingFull', 'Battery'), ('EvStation', 'EV Station'), ('Analytics', 'Analytics'), ('Dashboard', 'Dashboard'), ('Memory', 'Memory'), ('Storage', 'Server / Storage'), ('Cloud', 'Cloud'), ('Wifi', 'IoT / Wifi'), ('Psychology', 'AI / Brain'), ('AutoAwesome', 'AI / Sparkles'), ('Business', 'Company'), ('Factory', 'Factory'), ('Engineering', 'Engineering'), ('Science', 'R&D'), ('CurrencyRupee', 'Indian Rupee'), ('AccountBalance', 'Finance'), ('Handshake', 'Partnership'), ('EmojiObjects', 'Innovation'), ('Timeline', 'Timeline'), ('Star', 'Star'), ('Work', 'Jobs'), ('WorkspacePremiumOutlined', 'Award / Premium'), ('EmojiEventsOutlined', 'Trophy / Event'), ('LinkedIn', 'LinkedIn')], 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('num', 17), ('title', 5), ('description', 1), ('icon', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'min_num': 1}), 21: ('wagtail.blocks.StructBlock', [[('heading', 15), ('description', 16), ('steps', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'required': False}), 23: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload an mp4 file', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'help_text': '…or a hosted video URL (YouTube/Vimeo/CDN) instead of uploading', 'required': False}), 25: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Thumbnail shown before play', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 22), ('description', 16), ('video_file', 23), ('video_url', 24), ('poster_image', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': "2-letter avatar e.g. 'AS'", 'max_length': 2}), 29: ('wagtail.blocks.StructBlock', [[('quote', 1), ('name', 5), ('role', 22), ('company', 22), ('initials', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'min_num': 1}), 31: ('wagtail.blocks.StructBlock', [[('heading', 27), ('items', 30)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': "Tailwind bg class e.g. 'bg-primary'", 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('value', 5), ('suffix', 22), ('label', 5)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {'min_num': 1}), 35: ('wagtail.blocks.StructBlock', [[('heading', 22), ('bg', 32), ('stats', 34)]], {}), 36: ('wagtail.blocks.RichTextBlock', (), {}), 37: ('wagtail.blocks.StructBlock', [[('heading', 22), ('description', 36), ('note', 22)]], {}), 38: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 39: ('wagtail.blocks.StructBlock', [[('title', 5), ('document', 38), ('note', 22)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {'min_num': 1}), 41: ('wagtail.blocks.StructBlock', [[('heading', 22), ('documents', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'General Questions'", 'required': False}), 43: ('wagtail.blocks.StructBlock', [[('section', 42), ('q', 5), ('a', 1)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {'min_num': 1}), 45: ('wagtail.blocks.StructBlock', [[('heading', 22), ('items', 44)]], {}), 46: ('wagtail.blocks.StructBlock', [[('heading', 5), ('description', 16), ('primary_cta_text', 22), ('primary_cta_link', 22), ('secondary_cta_text', 22), ('secondary_cta_link', 22)]], {})}),
        ),
        migrations.AddField(
            model_name='productpage',
            name='body',
            field=wagtail.fields.StreamField([('overview', 3), ('capabilities', 7), ('tech_highlights', 14), ('deployment_steps', 21), ('video_section', 26), ('testimonials_section', 31), ('stats', 35), ('compliance_note', 37), ('documents', 41), ('faq_section', 45), ('cta', 46)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Overview', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.ListBlock', (1,), {'min_num': 1}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('paragraphs', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Capabilities', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {'min_num': 1}), 7: ('wagtail.blocks.StructBlock', [[('heading', 4), ('items', 6)]], {}), 8: ('wagtail.blocks.CharBlock', (), {'default': 'Built for Reliability', 'required': False}), 9: ('wagtail.blocks.TextBlock', (), {'default': "Purpose-engineered for the complexity of India's power infrastructure — built to last and scale.", 'required': False}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Protocol Support'"}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'Modbus, DNP3, IEC 61850'"}), 12: ('wagtail.blocks.StructBlock', [[('title', 10), ('description', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('eyebrow', 8), ('intro', 9), ('items', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'default': "How It's Deployed", 'required': False}), 16: ('wagtail.blocks.TextBlock', (), {'required': False}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': "'01', '02', etc.", 'max_length': 3}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('LanguageOutlined', 'Language / Globe'), ('ShieldOutlined', 'Shield'), ('VerifiedOutlined', 'Verified'), ('BoltOutlined', 'Bolt (outlined)'), ('SecurityOutlined', 'Security'), ('CheckCircleOutlined', 'Check Circle'), ('EngineeringOutlined', 'Engineering'), ('MemoryOutlined', 'Memory'), ('DescriptionOutlined', 'Description'), ('GavelOutlined', 'Gavel'), ('ArticleOutlined', 'Article'), ('PlayCircleOutlined', 'Play Circle'), ('RssFeedOutlined', 'RSS Feed'), ('HelpOutlined', 'Help / FAQ'), ('MicOutlined', 'Microphone / Podcast'), ('Bolt', 'Bolt (filled)'), ('TrendingUp', 'Trending Up'), ('Groups', 'Groups / Team'), ('LocationOn', 'Location'), ('Phone', 'Phone'), ('Email', 'Email'), ('Chat', 'Chat / WhatsApp'), ('ElectricBolt', 'Electric Bolt'), ('SolarPower', 'Solar Power'), ('WindPower', 'Wind Power'), ('BatteryChargingFull', 'Battery'), ('EvStation', 'EV Station'), ('Analytics', 'Analytics'), ('Dashboard', 'Dashboard'), ('Memory', 'Memory'), ('Storage', 'Server / Storage'), ('Cloud', 'Cloud'), ('Wifi', 'IoT / Wifi'), ('Psychology', 'AI / Brain'), ('AutoAwesome', 'AI / Sparkles'), ('Business', 'Company'), ('Factory', 'Factory'), ('Engineering', 'Engineering'), ('Science', 'R&D'), ('CurrencyRupee', 'Indian Rupee'), ('AccountBalance', 'Finance'), ('Handshake', 'Partnership'), ('EmojiObjects', 'Innovation'), ('Timeline', 'Timeline'), ('Star', 'Star'), ('Work', 'Jobs'), ('WorkspacePremiumOutlined', 'Award / Premium'), ('EmojiEventsOutlined', 'Trophy / Event'), ('LinkedIn', 'LinkedIn')], 'required': False}), 19: ('wagtail.blocks.StructBlock', [[('num', 17), ('title', 5), ('description', 1), ('icon', 18)]], {}), 20: ('wagtail.blocks.ListBlock', (19,), {'min_num': 1}), 21: ('wagtail.blocks.StructBlock', [[('heading', 15), ('description', 16), ('steps', 20)]], {}), 22: ('wagtail.blocks.CharBlock', (), {'required': False}), 23: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'help_text': 'Upload an mp4 file', 'required': False}), 24: ('wagtail.blocks.URLBlock', (), {'help_text': '…or a hosted video URL (YouTube/Vimeo/CDN) instead of uploading', 'required': False}), 25: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Thumbnail shown before play', 'required': False}), 26: ('wagtail.blocks.StructBlock', [[('heading', 22), ('description', 16), ('video_file', 23), ('video_url', 24), ('poster_image', 25)]], {}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'What Our Clients Say', 'required': False}), 28: ('wagtail.blocks.CharBlock', (), {'help_text': "2-letter avatar e.g. 'AS'", 'max_length': 2}), 29: ('wagtail.blocks.StructBlock', [[('quote', 1), ('name', 5), ('role', 22), ('company', 22), ('initials', 28)]], {}), 30: ('wagtail.blocks.ListBlock', (29,), {'min_num': 1}), 31: ('wagtail.blocks.StructBlock', [[('heading', 27), ('items', 30)]], {}), 32: ('wagtail.blocks.CharBlock', (), {'help_text': "Tailwind bg class e.g. 'bg-primary'", 'required': False}), 33: ('wagtail.blocks.StructBlock', [[('value', 5), ('suffix', 22), ('label', 5)]], {}), 34: ('wagtail.blocks.ListBlock', (33,), {'min_num': 1}), 35: ('wagtail.blocks.StructBlock', [[('heading', 22), ('bg', 32), ('stats', 34)]], {}), 36: ('wagtail.blocks.RichTextBlock', (), {}), 37: ('wagtail.blocks.StructBlock', [[('heading', 22), ('description', 36), ('note', 22)]], {}), 38: ('wagtail.documents.blocks.DocumentChooserBlock', (), {'required': False}), 39: ('wagtail.blocks.StructBlock', [[('title', 5), ('document', 38), ('note', 22)]], {}), 40: ('wagtail.blocks.ListBlock', (39,), {'min_num': 1}), 41: ('wagtail.blocks.StructBlock', [[('heading', 22), ('documents', 40)]], {}), 42: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'General Questions'", 'required': False}), 43: ('wagtail.blocks.StructBlock', [[('section', 42), ('q', 5), ('a', 1)]], {}), 44: ('wagtail.blocks.ListBlock', (43,), {'min_num': 1}), 45: ('wagtail.blocks.StructBlock', [[('heading', 22), ('items', 44)]], {}), 46: ('wagtail.blocks.StructBlock', [[('heading', 5), ('description', 16), ('primary_cta_text', 22), ('primary_cta_link', 22), ('secondary_cta_text', 22), ('secondary_cta_link', 22)]], {})}),
        ),
        migrations.RunPython(
            migrate_product_and_innovation_bodies,
            reverse_irreversible,
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='cta',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='gradient',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='innovationpage',
            name='tech_highlights',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='capabilities',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='cta',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='gradient',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='productpage',
            name='tech_highlights',
        ),
    ]
