# Generated by Django 5.1.15 on 2026-09-14 12:25

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_productpage_innovationpage_body'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('hide_footer_cta', models.BooleanField(default=False)),
                ('body', wagtail.fields.StreamField([('hero', 5), ('faq_section', 10), ('cta', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Eyebrow label above headline', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('heading', 1), ('description', 2), ('cta_text', 3), ('cta_link', 3), ('background_image', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'General Questions'", 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('section', 6), ('q', 1), ('a', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('heading', 3), ('items', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('heading', 1), ('description', 2), ('primary_cta_text', 3), ('primary_cta_link', 3), ('secondary_cta_text', 3), ('secondary_cta_link', 3)]], {})})),
            ],
            options={
                'verbose_name': 'FAQ Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HowWeWorkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('meta_keywords', models.TextField(blank=True)),
                ('hide_footer_cta', models.BooleanField(default=False)),
                ('body', wagtail.fields.StreamField([('hero', 5), ('how_we_work', 17), ('cta', 18)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Eyebrow label above headline', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('heading', 1), ('description', 2), ('cta_text', 3), ('cta_link', 3), ('background_image', 4)]], {}), 6: ('wagtail.blocks.CharBlock', (), {'help_text': "'01' through '06'", 'max_length': 3}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hex color for step number badge'}), 9: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hex color for timeline dot border'}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hex color for connector line'}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': 'Hex color for card border'}), 12: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('right', 'Right'), ('left', 'Left')]}), 13: ('wagtail.blocks.StructBlock', [[('num', 6), ('title', 1), ('desc', 7), ('badge_color', 8), ('dot_color', 9), ('connector_color', 10), ('card_border', 11), ('image', 4), ('side', 12)]], {}), 14: ('wagtail.blocks.ListBlock', (13,), {'min_num': 1}), 15: ('wagtail.blocks.StructBlock', [[('title', 1), ('desc', 7)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {'required': False}), 17: ('wagtail.blocks.StructBlock', [[('steps', 14), ('principles', 16)]], {}), 18: ('wagtail.blocks.StructBlock', [[('heading', 1), ('description', 2), ('primary_cta_text', 3), ('primary_cta_link', 3), ('secondary_cta_text', 3), ('secondary_cta_link', 3)]], {})})),
            ],
            options={
                'verbose_name': 'How We Work Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
