# Generated by Django 5.1.15 on 2026-09-15 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_rename_productpage_portfoliopage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfoliopage',
            options={'verbose_name': 'Portfolio Page'},
        ),
    ]
