# Generated by Django 5.1.15 on 2026-09-15 08:59

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_portfoliopage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelearnsectionpage',
            name='body',
            field=wagtail.fields.StreamField([('hero', 5), ('card_section', 10), ('stats', 14), ('side_section', 21), ('intro', 23), ('cta', 24)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Eyebrow label above headline', 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.TextBlock', (), {'required': False}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('label', 0), ('heading', 1), ('description', 2), ('cta_text', 3), ('cta_link', 3), ('background_image', 4)]], {}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('LanguageOutlined', 'Language / Globe'), ('ShieldOutlined', 'Shield'), ('VerifiedOutlined', 'Verified'), ('BoltOutlined', 'Bolt (outlined)'), ('SecurityOutlined', 'Security'), ('CheckCircleOutlined', 'Check Circle'), ('EngineeringOutlined', 'Engineering'), ('MemoryOutlined', 'Memory'), ('DescriptionOutlined', 'Description'), ('GavelOutlined', 'Gavel'), ('ArticleOutlined', 'Article'), ('PlayCircleOutlined', 'Play Circle'), ('RssFeedOutlined', 'RSS Feed'), ('HelpOutlined', 'Help / FAQ'), ('MicOutlined', 'Microphone / Podcast'), ('Bolt', 'Bolt (filled)'), ('TrendingUp', 'Trending Up'), ('Groups', 'Groups / Team'), ('LocationOn', 'Location'), ('Phone', 'Phone'), ('Email', 'Email'), ('Chat', 'Chat / WhatsApp'), ('ElectricBolt', 'Electric Bolt'), ('SolarPower', 'Solar Power'), ('WindPower', 'Wind Power'), ('BatteryChargingFull', 'Battery'), ('EvStation', 'EV Station'), ('Analytics', 'Analytics'), ('Dashboard', 'Dashboard'), ('Memory', 'Memory'), ('Storage', 'Server / Storage'), ('Cloud', 'Cloud'), ('Wifi', 'IoT / Wifi'), ('Psychology', 'AI / Brain'), ('AutoAwesome', 'AI / Sparkles'), ('Business', 'Company'), ('Factory', 'Factory'), ('Engineering', 'Engineering'), ('Science', 'R&D'), ('CurrencyRupee', 'Indian Rupee'), ('AccountBalance', 'Finance'), ('Handshake', 'Partnership'), ('EmojiObjects', 'Innovation'), ('Timeline', 'Timeline'), ('Star', 'Star'), ('Work', 'Jobs'), ('WorkspacePremiumOutlined', 'Award / Premium'), ('EmojiEventsOutlined', 'Trophy / Event'), ('LinkedIn', 'LinkedIn')], 'required': False}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('icon', 6), ('title', 1), ('description', 7), ('note', 3), ('link', 3), ('gradient', 3), ('icon_bg', 3)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'min_num': 1}), 10: ('wagtail.blocks.StructBlock', [[('heading', 3), ('description', 2), ('cards', 9)]], {}), 11: ('wagtail.blocks.CharBlock', (), {'help_text': "Tailwind bg class e.g. 'bg-primary'", 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('value', 1), ('suffix', 3), ('label', 1)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'min_num': 1}), 14: ('wagtail.blocks.StructBlock', [[('heading', 3), ('bg', 11), ('stats', 13)]], {}), 15: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 17: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('left', 'Left'), ('right', 'Right')]}), 18: ('wagtail.blocks.StructBlock', [[('image', 16), ('alt', 3), ('position', 17)]], {}), 19: ('wagtail.blocks.StructBlock', [[('bold_title', 1), ('point', 7)]], {}), 20: ('wagtail.blocks.StreamBlock', [[('bullet', 19), ('text', 7)]], {'required': False}), 21: ('wagtail.blocks.StructBlock', [[('heading', 3), ('description', 15), ('image', 18), ('body_blocks', 20)]], {}), 22: ('wagtail.blocks.RichTextBlock', (), {}), 23: ('wagtail.blocks.StructBlock', [[('heading', 3), ('description', 22), ('note', 3)]], {}), 24: ('wagtail.blocks.StructBlock', [[('heading', 1), ('description', 2), ('primary_cta_text', 3), ('primary_cta_link', 3), ('secondary_cta_text', 3), ('secondary_cta_link', 3)]], {})}),
        ),
        migrations.AlterField(
            model_name='gelearnsectionpage',
            name='section_type',
            field=models.CharField(blank=True, choices=[('technology', 'Technology Deep Dives'), ('case-studies', 'Case Studies'), ('tenders', 'Tenders'), ('whitepapers', 'Whitepapers'), ('videos', 'Videos'), ('blog', 'Blog'), ('podcasts', 'Podcasts')], help_text='Controls which snippet list the frontend queries', max_length=30),
        ),
    ]
