# Generated by Django 5.1.15 on 2026-09-19 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0025_alter_contentpage_body_alter_sectionpage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='careerspage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='careerspage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='careerspage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='contentpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='gelearnindexpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='gelearnindexpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='gelearnindexpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='gelearnsectionpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='gelearnsectionpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='gelearnsectionpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='jobpage',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='sectionpage',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='sectionpage',
            name='meta_keywords',
        ),
        migrations.RemoveField(
            model_name='sectionpage',
            name='meta_title',
        ),
    ]
