# Generated by Django 5.1.15 on 2026-09-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_userblogpost_image_uservideopost_thumbnail_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='category_bg',
        ),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='category_text',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='category_color',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='category_text_color',
        ),
        migrations.AddField(
            model_name='userblogpost',
            name='other_topic',
            field=models.CharField(blank=True, help_text='Author-suggested new topic, reviewed alongside the rest of the submission', max_length=100),
        ),
        migrations.AddField(
            model_name='uservideopost',
            name='duration',
            field=models.CharField(blank=True, help_text="e.g. '14:32 min' — matches VideoItem.duration", max_length=20),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='topic',
            field=models.CharField(help_text="e.g. 'Policy', 'Engineering' — legacy, superseded by Topics below", max_length=100),
        ),
        migrations.AlterField(
            model_name='userblogpost',
            name='topic',
            field=models.CharField(blank=True, help_text='Legacy — superseded by Topics below', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='posts', to='pages.topic'),
        ),
        migrations.AddField(
            model_name='userblogpost',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='submissions', to='pages.topic'),
        ),
    ]
