# Generated by Django 5.1.15 on 2026-09-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_seed_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
