# Generated by Django 5.1.15 on 2026-09-29 10:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def tiers_to_access(apps, schema_editor):
    """Any tier above the public "free" one (rank 0) becomes members-only.
    No tier carried a price, so nothing maps to paid — set that per item."""
    for model_name in ("VideoItem", "PodcastEpisode"):
        Model = apps.get_model("pages", model_name)
        Model.objects.filter(required_tier__rank__gt=0).update(access="members")


def access_to_tiers(apps, schema_editor):
    MembershipTier = apps.get_model("accounts", "MembershipTier")
    registered = MembershipTier.objects.filter(slug="registered").first()
    if registered is None:
        return
    for model_name in ("VideoItem", "PodcastEpisode"):
        Model = apps.get_model("pages", model_name)
        Model.objects.exclude(access="free").update(required_tier=registered)


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_rename_geacademy_research_policies'),
        # MembershipTier must still exist while tiers are copied into access.
        ('accounts', '0008_display_name_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='access',
            field=models.CharField(choices=[('free', 'Free — anyone'), ('members', 'Members only — any signed-in account'), ('paid', 'Paid — purchase required')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='currency',
            field=models.CharField(default='INR', help_text='ISO code, e.g. INR.', max_length=3),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for paid content.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='access',
            field=models.CharField(choices=[('free', 'Free — anyone'), ('members', 'Members only — any signed-in account'), ('paid', 'Paid — purchase required')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='currency',
            field=models.CharField(default='INR', help_text='ISO code, e.g. INR.', max_length=3),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for paid content.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='access',
            field=models.CharField(choices=[('free', 'Free — anyone'), ('members', 'Members only — any signed-in account'), ('paid', 'Paid — purchase required')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='currency',
            field=models.CharField(default='INR', help_text='ISO code, e.g. INR.', max_length=3),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for paid content.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.RunPython(tiers_to_access, access_to_tiers),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='required_tier',
        ),
        migrations.RemoveField(
            model_name='videoitem',
            name='required_tier',
        ),
    ]
