# Generated by Django 5.1.15 on 2026-09-29 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def guest_user_to_collaborators(apps, schema_editor):
    """The single linked guest becomes the episode's first collaborator."""
    PodcastEpisode = apps.get_model("pages", "PodcastEpisode")
    for episode in PodcastEpisode.objects.exclude(guest_user=None):
        episode.collaborators.add(episode.guest_user_id)


def collaborators_to_guest_user(apps, schema_editor):
    PodcastEpisode = apps.get_model("pages", "PodcastEpisode")
    for episode in PodcastEpisode.objects.all():
        first = episode.collaborators.order_by("pk").first()
        if first is not None:
            episode.guest_user_id = first.pk
            episode.save(update_fields=["guest_user"])


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_expert_wording'),
        ('pages', '0035_access_replaces_tiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='casestudy',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Publishing company — shown with its logo. Leave empty for Genex editorial content made here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='casestudy',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Company staff account that published this from the Studio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='collaborators',
            field=models.ManyToManyField(blank=True, help_text='Professionals featured in this episode — it appears on their profiles.', limit_choices_to={'account_type': 'professional'}, related_name='podcast_collaborations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Publishing company — shown with its logo. Leave empty for Genex editorial content made here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Company staff account that published this from the Studio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='techarticle',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Publishing company — shown with its logo. Leave empty for Genex editorial content made here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='techarticle',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Company staff account that published this from the Studio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tender',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Publishing company — shown with its logo. Leave empty for Genex editorial content made here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='tender',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Company staff account that published this from the Studio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Publishing company — shown with its logo. Leave empty for Genex editorial content made here.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_items', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Company staff account that published this from the Studio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
            migrations.RunPython(guest_user_to_collaborators, collaborators_to_guest_user),
        migrations.RemoveField(
            model_name='podcastepisode',
            name='guest_user',
        ),
    ]
