# Generated by Django 5.1.15 on 2026-09-30 05:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def sanitize_existing_submissions(apps, schema_editor):
    """Clean HTML already stored from Professional blog submissions and the posts published from them."""
    from pages.richtext import sanitize_submission_html

    UserBlogPost = apps.get_model("pages", "UserBlogPost")
    BlogPost = apps.get_model("pages", "BlogPost")
    for submission in UserBlogPost.objects.all():
        cleaned = sanitize_submission_html(submission.body)
        if cleaned != submission.body:
            submission.body = cleaned
            submission.save(update_fields=["body"])
    for post in BlogPost.objects.filter(submission_source__isnull=False):
        blocks = [dict(b) for b in post.body.raw_data]
        changed = False
        for block in blocks:
            if block.get("type") == "rich_text" and isinstance(block.get("value"), str):
                cleaned = sanitize_submission_html(block["value"])
                if cleaned != block["value"]:
                    block["value"], changed = cleaned, True
        if changed:
            post.body = blocks
            post.save(update_fields=["body"])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0036_company_publisher_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogpost',
            name='access',
            field=models.CharField(choices=[('free', 'Free — anyone'), ('members', 'Members only — any signed-in account'), ('paid', 'Paid — purchase required')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='userblogpost',
            name='currency',
            field=models.CharField(default='INR', help_text='ISO code, e.g. INR.', max_length=3),
        ),
        migrations.AddField(
            model_name='userblogpost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for paid content.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AddField(
            model_name='uservideopost',
            name='access',
            field=models.CharField(choices=[('free', 'Free — anyone'), ('members', 'Members only — any signed-in account'), ('paid', 'Paid — purchase required')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='uservideopost',
            name='currency',
            field=models.CharField(default='INR', help_text='ISO code, e.g. INR.', max_length=3),
        ),
        migrations.AddField(
            model_name='uservideopost',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required for paid content.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.RunPython(sanitize_existing_submissions, migrations.RunPython.noop),
    ]
