# Generated by Django 5.1.15 on 2026-10-01 06:22

import django.db.models.deletion
from django.db import migrations, models


def parse_deadline(text):
    """'30 / 06 / 2026', '30/06/2026' or '30-06-26' → date (day first); None if unreadable."""
    import datetime
    import re
    parts = re.findall(r"\d+", text or "")
    if len(parts) != 3:
        return None
    day, month, year = (int(p) for p in parts)
    if year < 100:
        year += 2000
    try:
        return datetime.date(year, month, day)
    except ValueError:
        return None


def deadline_text_to_date(apps, schema_editor):
    Tender = apps.get_model("pages", "Tender")
    for tender in Tender.objects.all():
        tender.deadline_date = parse_deadline(tender.deadline)
        tender.save(update_fields=["deadline_date"])


def deadline_date_to_text(apps, schema_editor):
    Tender = apps.get_model("pages", "Tender")
    for tender in Tender.objects.all():
        tender.deadline = tender.deadline_date.strftime("%d / %m / %Y") if tender.deadline_date else ""
        tender.save(update_fields=["deadline"])


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_submission_access'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
            ],
            options={
                'verbose_name': 'Topic Group',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='casestudy',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Used for topic pages, the Explore menu and recommendations.', related_name='research_items', to='pages.topic'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Used for topic pages, the Explore menu and recommendations.', related_name='podcasts', to='pages.topic'),
        ),
        migrations.AddField(
            model_name='techarticle',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Used for topic pages, the Explore menu and recommendations.', related_name='geacademy_articles', to='pages.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order within its group. Lower numbers come first.'),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='videoitem',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Used for topic pages, the Explore menu and recommendations.', related_name='videos', to='pages.topic'),
        ),
        migrations.AddField(
            model_name='whitepaper',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='Used for topic pages, the Explore menu and recommendations.', related_name='whitepapers', to='pages.topic'),
        ),
        # Tender.deadline: free text ("30 / 06 / 2026") becomes a real date.
        # Copy through a temporary column so existing deadlines survive (and
        # are written back as text if this migration is reversed).
        migrations.AddField(
            model_name='tender',
            name='deadline_date',
            field=models.DateField(null=True),
        ),
        migrations.RunPython(deadline_text_to_date, deadline_date_to_text),
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.RemoveField(
            model_name='tender',
            name='deadline',
        ),
        migrations.RenameField(
            model_name='tender',
            old_name='deadline_date',
            new_name='deadline',
        ),
        migrations.AlterField(
            model_name='tender',
            name='deadline',
            field=models.DateField(help_text='Last date to submit. Drives "closes in N days" on GeLearn.', null=True),
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=600)),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(blank=True, help_text="e.g. 'SCADA Engineer'", max_length=150)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Only active testimonials appear on GeLearn.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.AddField(
            model_name='topic',
            name='group',
            field=models.ForeignKey(blank=True, help_text="Topics without a group stay usable but don't appear in the Explore menu.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='pages.topicgroup'),
        ),
    ]
