# Generated by Django 5.1.15 on 2026-10-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0047_seed_promo_audience'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, help_text="One or two sentences shown at the top of the topic's page on GeLearn.", max_length=400),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ForeignKey(blank=True, help_text="Optional picture for the topic's page and cards.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
