# Generated by Django 5.1.15 on 2026-09-29 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive companies disappear from the registration dropdown and their professionals lose the verified badge. Use this instead of deleting.'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Small square logo (SVG or PNG) shown next to everything this company or its verified experts publish.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
