# Generated by Django 5.1.15 on 2026-10-01 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        ('organizations', '0002_expert_wording'),
        ('pages', '0037_submission_access'),
        ('wagtailimages', '0027_image_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='company',
            field=models.ForeignKey(blank=True, help_text="Set for courses a company builds in Company Studio; shown as 'Course by <company>'. Empty for a Professional's own course.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='organizations.company'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='featured',
            field=models.BooleanField(default=False, help_text='Editorial pick; set by Admin only.'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=12),
        ),
        migrations.AddField(
            model_name='playlist',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='courses', to='pages.topic'),
        ),
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=130, unique=True)),
                ('summary', models.TextField(blank=True, help_text='One or two sentences on what the role does.', max_length=300)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers come first.')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Career Role',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='playlist',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='courses', to='learning.careerrole'),
        ),
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('starts_at', models.DateTimeField(help_text='Date and time in IST.')),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('speaker_name', models.CharField(blank=True, help_text="Outside speaker's name.", max_length=150)),
                ('speaker_role', models.CharField(blank=True, max_length=150)),
                ('registration_url', models.URLField(help_text='Where people register or join (opens in a new tab).')),
                ('is_published', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, help_text='Hosting company. Empty means Genex.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='live_sessions', to='organizations.company')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('speaker', models.ForeignKey(blank=True, help_text='A Professional on GeLearn. Leave empty and use the name field for an outside speaker.', limit_choices_to={'account_type': 'professional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
                ('topics', models.ManyToManyField(blank=True, related_name='live_sessions', to='pages.topic')),
            ],
            options={
                'verbose_name': 'Live Session',
                'ordering': ['starts_at'],
            },
        ),
    ]
