# Generated by Django 5.1.15 on 2026-10-05 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_seed_career_roles'),
        ('pages', '0047_seed_promo_audience'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='playlistitem',
            name='playlist_item_exactly_one_target',
        ),
        migrations.AddField(
            model_name='careerrole',
            name='duties',
            field=models.TextField(blank=True, help_text="One responsibility per line. Shown as a list on the role's page.", verbose_name='What this role does'),
        ),
        migrations.AddField(
            model_name='careerrole',
            name='topics',
            field=models.ManyToManyField(blank=True, help_text='The topics this role draws on; shown as "Skills you\'ll build".', related_name='career_roles', to='pages.topic', verbose_name='Skills'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.techarticle'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.podcastepisode'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.casestudy'),
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='whitepaper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pages.whitepaper'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('article__isnull', True), ('podcast__isnull', True), ('post__isnull', True), ('research__isnull', True), ('video__isnull', False), ('whitepaper__isnull', True)), models.Q(('article__isnull', True), ('podcast__isnull', True), ('post__isnull', False), ('research__isnull', True), ('video__isnull', True), ('whitepaper__isnull', True)), models.Q(('article__isnull', False), ('podcast__isnull', True), ('post__isnull', True), ('research__isnull', True), ('video__isnull', True), ('whitepaper__isnull', True)), models.Q(('article__isnull', True), ('podcast__isnull', True), ('post__isnull', True), ('research__isnull', False), ('video__isnull', True), ('whitepaper__isnull', True)), models.Q(('article__isnull', True), ('podcast__isnull', True), ('post__isnull', True), ('research__isnull', True), ('video__isnull', True), ('whitepaper__isnull', False)), models.Q(('article__isnull', True), ('podcast__isnull', False), ('post__isnull', True), ('research__isnull', True), ('video__isnull', True), ('whitepaper__isnull', True)), _connector='OR'), name='playlist_item_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('article__isnull', False)), fields=('playlist', 'article'), name='playlist_unique_article'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('research__isnull', False)), fields=('playlist', 'research'), name='playlist_unique_research'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('whitepaper__isnull', False)), fields=('playlist', 'whitepaper'), name='playlist_unique_whitepaper'),
        ),
        migrations.AddConstraint(
            model_name='playlistitem',
            constraint=models.UniqueConstraint(condition=models.Q(('podcast__isnull', False)), fields=('playlist', 'podcast'), name='playlist_unique_podcast'),
        ),
    ]
