# Generated by Django 5.1.15 on 2026-10-06 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_seed_role_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='instructors',
            field=models.ManyToManyField(blank=True, help_text="Company courses only: up to 3 of the company's verified Professionals. A Professional's own course always shows its owner.", related_name='taught_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='language',
            field=models.CharField(default='English', max_length=40),
        ),
        migrations.AddField(
            model_name='playlist',
            name='outcomes',
            field=models.JSONField(blank=True, default=list, help_text='A list of up to 8 short outcomes.', verbose_name="What you'll learn"),
        ),
        migrations.AddField(
            model_name='playlist',
            name='prerequisites',
            field=models.JSONField(blank=True, default=list, help_text='A list of up to 5 things learners should know first.', verbose_name='Before you start'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='summary',
            field=models.CharField(blank=True, help_text='One or two sentences shown under the title and on course cards.', max_length=220),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='About this course'),
        ),
        migrations.CreateModel(
            name='CourseFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(max_length=1000)),
                ('position', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='learning.playlist')),
            ],
            options={
                'verbose_name': 'Course FAQ',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CourseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveIntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='learning.playlist')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='playlistitem',
            name='module',
            field=models.ForeignKey(blank=True, help_text="Empty when the course has no modules, or the lesson isn't in one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='learning.coursemodule'),
        ),
    ]
