# Generated by Django 5.1.15 on 2026-10-06 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_course_owner_protect'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('body', models.TextField(blank=True, max_length=2000, verbose_name='review')),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('hidden', 'Hidden by Genex')], db_index=True, default='visible', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.playlist', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course review',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['playlist', 'status'], name='learning_co_playlis_e596c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'playlist'), name='one_review_per_course')],
            },
        ),
    ]
