# Generated by Django 5.1.15 on 2026-10-07 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_self_enrolments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changes', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('rejected', 'Sent back')], db_index=True, default='pending', max_length=10)),
                ('rejection_reason', models.TextField(blank=True, help_text='Shown to the author when the changes are sent back.')),
                ('submitted_at', models.DateTimeField(help_text='When the author last saved changes.')),
                ('playlist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision', to='learning.playlist', verbose_name='course')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending course change',
            },
        ),
    ]
