# Generated by Django 5.1.15 on 2026-10-08 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0011_review_replies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Public ID, e.g. GL-7K3X-9QF2; also the verify address.', max_length=16, unique=True)),
                ('learner_name', models.CharField(help_text='As printed. The learner can correct it once.', max_length=80)),
                ('name_corrected', models.BooleanField(default=False, help_text='The learner has used their one name correction.')),
                ('snapshot', models.JSONField(default=dict, help_text='Course, instructors and publisher as printed.')),
                ('issued_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('revoked', 'Revoked')], db_index=True, default='valid', max_length=10)),
                ('revoked_reason', models.CharField(blank=True, max_length=300)),
                ('playlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='learning.playlist', verbose_name='course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='learner')),
            ],
            options={
                'ordering': ['-issued_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'playlist'), name='one_certificate_per_course')],
            },
        ),
    ]
